#!/usr/bin/env bash

command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.
Aborting."; exit 1; }
command -v wget >/dev/null 2>&1 || { echo >&2 "Program 'wget' required but is not installed.
Aborting."; exit 1; }

# To use this script you need to create an API key here https://home.openweathermap.org
# You need to put your Open Weather APIKEY here:
APIKEY=$OPEN_WEATHER
# find your City ID here: https://openweathermap.org/
# search for your city and copy the ID from the URL inside the browser.
CITY_ID="5110302"
# boco 5574991
# bk 5110302
URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&units=imperial&APPID=${APIKEY}"

WEATHER_RESPONSE=$(wget -qO- "${URL}")
WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.weather[0].main' | sed 's/"//g')
WEATHER_TEMP=$(printf "%.0f" $(echo $WEATHER_RESPONSE | jq '.main.temp'))
WEATHER_HUMIDITY=$(echo $WEATHER_RESPONSE | jq '.main.humidity')
WIND_DIR=$( echo "$WEATHER_RESPONSE" | jq '.wind.deg')
WIND_SPEED=$( echo "$WEATHER_RESPONSE" | jq '.wind.speed')
FEELS=$(echo $WEATHER_RESPONSE | jq '.weather[0].description' | sed 's/"//g')
WIND_SPEED=$(awk "BEGIN {print int($WIND_SPEED)}")
WIND_DIR=$(awk "BEGIN {print int(($WIND_DIR % 360)/22.5)}")
DIR_ARRAY=( N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N )
DIR_ICONS=(                  )
WIND_DIR=${DIR_ICONS[WIND_DIR]}
# GEN_NAME=$()
case $WEATHER_CONDITION in
  'Clouds')
    WEATHER_ICON=" "
    ;;
  'Rain')
    WEATHER_ICON=""
    ;;
  'Drizzle')
    WEATHER_ICON=""
    ;;
  'Thunderstorm')
    WEATHER_ICON=""
    ;;
  'Snow')
    WEATHER_ICON=""
    ;;
  'Mist')
    WEATHER_ICON=""
    ;;
  'Fog')
    WEATHER_ICON=""
    ;;
  'Smoke')
    WEATHER_ICON=""
    ;;
  'Haze')
    WEATHER_ICON=""
    ;;
  *)
    WEATHER_ICON=""
    ;;
esac

echo "<span font_weight='bold'>${WEATHER_ICON}</span> <span font_weight='heavy'>${FEELS}</span> <span font_weight='bold'>${WEATHER_TEMP}°</span> <span font_weight='bold'>${WEATHER_HUMIDITY}%</span> <span></span> <span font_weight='bold'>${WIND_SPEED}</span><span>${WIND_DIR}</span> "
